### ISSUE TITLE
Evaluation of Bounswe Repos - Traceability Graph 

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#10]
### Issue Description

As mentioned and documented in Issue #9, Bounswe projects Learnify and BUcademy have been scanned and traceability links between requirements and software artifacts are noted in a text format. For these projects, a traceability graph with various nodes and links to visualize the traces between artifacts needs to be drawn.

The graph may have several link types:

- Requirements to issues may have a "similarity" type of link.
- Issues to PRs may have an "implements" type of link.
- Commits to PR may have an "includes" type of link.

The graph may have several node types. This may include **requirement**, **issue**, **commit**.  

The nodes may have properties:

- The issue node may have a title and description.
- The requirement node may have vagueness, the number of nodes connected, 
- PRs may have the title, description, and merged status.
-  Commits may have messages. 

Other node and link types are welcomed along with discussed ones.

### Step Details

Projects that will be graphed are:
- [x] Learnify - @ersoykadir 
- [x] BUcademy - @codingAku 

### Final Actions

The graphs must be linked to the Wiki page for documentation purposes.

### Deadline of the Issue

26.03.2023 - 23.59

**Comment by ersoykadir** [comment]
The discussion notes from this week's meeting has been added [here](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Meeting-4---20.03.2023). Keep in mind those while consturcting the graph.

**Comment by codingAku** [comment]
The [initial graph](https://lucid.app/lucidchart/02f159f9-4d5c-4c94-a544-c4f2dfe4d904/edit?viewport_loc=234%2C-1358%2C3840%2C1848%2C0_0&invitationId=inv_303b079d-431a-489b-8785-69b197e0f77a) is complete. I will search for different requirements to link, and add necessary nodes. The final version will be documented to wiki with the notes.

**Comment by codingAku** [comment]
UPDATE: The graph has been enriched. The [wiki page](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Traceability-Graph-of-Bounswe-Projects) is created, and the traceability graph is documented and linked to the sidebar.
