### ISSUE TITLE
Keyword Extraction on Requirements

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#11]
### Issue Description

The traceability graphs are complete. However, the main search for similarity links were searching important keywords from requirement specifications on software artifacts. This process needs to be done automatically. 

For the purpose, the following methods may be used:

- Dependency parsing
- Part of speech parsing

### Step Details

Steps that will be performed:
- [x] Research keyword extraction methods
- [x] Test available engines
- [x] Document the effectiveness

### Final Actions

The documentation must be on Wiki.

### Deadline of the Issue

4.04.2023

**Comment by codingAku** [comment]
The documentation is present on [Wiki](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Automatization-of-Traceability-Graphs).

**Comment by codingAku** [comment]
The programs and the results have been pushed to the main branch. 
https://github.com/ersoykadir/Requirement-Traceability-Analysis/tree/main/keyword_extractors

**Comment by ersoykadir** [comment]
We have reviewed and discussed the keyword extraction and search at [meeting 6](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Meeting-6---03.04.2023). It will be improved with dependency parsing and some other techniques in coming weeks.
