### ISSUE TITLE
Keyword Extraction : Dependency Parsing Links

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#13]
### Issue Description

With Issue #11, the keywords of requirements for tracing is extracted. However, the initial trace results are noisy to operate. The noise needs to be reduced with more relevant keywords. One way to provide this is with dependency parsing links. 

### Step Details

Steps that will be performed:
- [x] Create a program that shows dependency parsing links.
- [x] Use the program on keywords extracted.
- [x] Increase the importance of keywords with parsing links.

### Final Actions

The findings need to be documented in Wiki page.

### Deadline of the Issue

10.04.2023 - 23.59

**Comment by codingAku** [comment]
The dependency parser program has been implemented, and the [Results for the requirements of BUcademy](https://github.com/ersoykadir/Requirement-Traceability-Analysis/blob/main/keyword_extractors/dependency_links.txt) have been added. The comparison and analysis of the usage will be discussed in Meeting 7.

Additionally, [word frequency program](https://github.com/ersoykadir/Requirement-Traceability-Analysis/blob/main/keyword_extractors/word_frequency.py) was implemented, to extend the stopword list.

**Comment by codingAku** [comment]
Update: The results of word frequency for 5 keywords and 10 keywords on BUcademy requirements are as follows:

![wrods](https://user-images.githubusercontent.com/64018144/230877671-ae011e60-c7b3-46b7-b8bc-41d580d6501c.jpg)

**Comment by codingAku** [comment]
Using the dependency links and Part-of-Speech Tagging, [enhanced keyword extractor pipeline](https://github.com/ersoykadir/Requirement-Traceability-Analysis/blob/main/keyword_extractors/dependency_parsing_custom_pipeline.py) implemented.

**Comment by ersoykadir** [comment]
First results with new keywords added to [repo](https://github.com/ersoykadir/Requirement-Traceability-Analysis/blob/main/traceResults/week9/trace_links.txt). 
First impressions:
- prefix and suffixes seems to effect the results, we might want to preprocess(stemming?) issue documents as well.
  - verification codes vs verification code
- noun phrases duplicates
  - for `email address` phrase, email is kept and address is removed from keywords. We should keep both or remove both.
- noun phrase triples, 
  - `email verification process`, produces two phrase like `email verification` and `verification process`
  - this can be improved, but do we want to improve?
- verb-obj pairs is constructed with single noun
  - `edit profile page`, produces edit page
  - `enter verification codes` produces enter codes
  - we can improve with verb-nounphrase, however enter codes might have higher recall!

**Comment by codingAku** [comment]
UPDATE: Keyword lemmatizer implemented in PR #17

**Comment by codingAku** [comment]
Keyword extraction completed.
