### ISSUE TITLE
Midterm Report

### ISSUE THREAD

**Issue by ersoykadir** [ersoykadir/Requirement-Traceability-Analysis#14]
### Issue Description

We need to prepare our midterm report. It will essentially contain what have we done so far. 
We already have on wiki:
- [Literature survey](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Similar-Researches), summarized papers
- [Observations](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Observations-and-Linkages-of-Software-Artifacts-on-Open-Source-Projects) on github repos and tools
- [Manual trace evaluation](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Evaluations-of-Bounswe-Projects) of bounswe repos
- [Manual traceability graph](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Traceability-Graph-of-Bounswe-Projects) built and visualized
- Initial protoype of [automating trace link search](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Traceability-Graph-of-Bounswe-Projects)
  - Keyword extraction, parsing of repository data and finding trace links
- First results for [keyword extraction](https://github.com/ersoykadir/Requirement-Traceability-Analysis/tree/main/keyword_extractors) and [trace links](https://github.com/ersoykadir/Requirement-Traceability-Analysis/tree/main/traceResults/week6)
- Meeting notes 
- Milestones

### Step Details

There are 7 sections to the report
- [x] Introduction
  - [x] Broad Impact
  - [x] Ethical Considerations
- [x] Project Definition and Planning
  - [x] Project Definition - `Ecenur`
  - [x] Project Planning - `Kadir`
    - Milestones and meeting notes
  - [x] Project Time and Resource Estimation
    - How long it will take?, What are the resources required? ([see](https://humble-bull-0d3.notion.site/Midterm-Report-821364331c4b46dda9bb9a426f478580))
  - [x] Success Criteria
  - [x] Risk Analysis
  - [x] Team Work (if applicable)
- [x] Related Work (Literature survey) - `Ecenur`
- [x] Methodology(Solution methods.)
- [x] Requirements Specification (Use case diagrams.)
- [x] Design
  - [x] Information Structure(ER Diagrams)
  - [x] Information Flow(Activity diagrams, sequence diagrams, Business Process Modeling Notation.)
  - [x] System Design(Class diagrams, module diagrams.) - `Kadir`
  - [x] User Interface Design (if applicable) 
- [x] Implementation and Testing
  - [x] Implementation
  - Testing TBD
  - Deployment TBD
- Results TBD
- Conclusion TBD

### Final Actions

- Review the overall report.
- Send the report to Advisors
- Submit the report through moodle(both students).

### Deadline of the Issue

09.04.2023 @23.59

**Comment by codingAku** [comment]
The [Midterm Report](https://github.com/ersoykadir/Requirement-Traceability-Analysis/blob/main/CMPE_492_MidtermReport.pdf) has been completed and submitted on 09.04.2023.
