### ISSUE TITLE
Creating a First Page for Wiki

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#2]
### Issue Description

A wiki first page is needed to describe the project. The page must include the title of the project, brief description, the aim and the contributors.

### Final Actions

Review for the adequacy is required.

### Deadline of the Issue

23.59 - 23.02.2023

**Comment by codingAku** [comment]
Please do see the [Home](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki) page in wiki.

**Comment by ersoykadir** [comment]
Looks convenient for now. We will update it as we improve.
