### ISSUE TITLE
Evaluation of Prototype Results

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#21]
### Issue Description

The initial prototype with captured traces exists. The next step is to compare the results with a set of ground truth and document the evaluation.

Initializing Ground Truth Set:
For this purpose, a subset of requirements from the Learnify App Repository will be selected and their traces will be documented. This will be a manual analysis made by @codingAku and @ersoykadir.
The selected requirement subset is as follows:
- `1.1.1.2.1.` Users shall provide their usernames and passwords to log in. - @codingAku 
- `1.1.1.4.2.` Users shall be authenticated after verification and be logged in. - @ersoykadir 
- `1.1.2.14.1.` Users shall be able to annotate post images and texts in learning spaces. @codingAku 
- `1.1.2.14.2.` Users shall be able to view annotations made by other users. - @ersoykadir 
- `1.1.2.15.1.` Users shall be able to see all learning spaces they created or enrolled in. - @codingAku 
- `1.1.3.2.5.1`. Participants shall be able to create community events for that learning space. - @codingAku 
- `1.1.2.2` Users shall be able to edit their profile page. - @ersoykadir 
- `1.1.3.2.7.1.` Participants of a learning space shall be able to create discussion posts. - @codingAku 

The results of semantically related traces in the software artifacts will be used as ground truth set for evaluation.

The results of initial prototype:

The tool will be run with two different trace selection methods; keyword extraction and word vectors. The results will be compared with the ground truth set to document **recall** and **precision** values.
 

### Step Details

Steps that will be performed:
- [x] Create ground truth set
- [x] Execute the tool with different trace capture methods
- [x] Document recall and precision values.

### Final Actions

The findings need to be documented in a tabular format.

### Deadline of the Issue

09.05.2023

**Comment by codingAku** [comment]
The results for keyword-extraction and parent mode:
![image](https://github.com/ersoykadir/Requirement-Traceability-Analysis/assets/64018144/190d35ce-f2b3-470e-9532-d16924700916)
The results for word-vector and parent-mode:
![image](https://github.com/ersoykadir/Requirement-Traceability-Analysis/assets/64018144/a189c504-5eff-41d4-9319-0335cb48a1f3)

**Comment by ersoykadir** [comment]
![image](https://github.com/ersoykadir/Requirement-Traceability-Analysis/assets/49765256/8c587461-384e-47cc-b901-575e8eee66a7)

**Comment by codingAku** [comment]
Recall and precision values documented to paper and submitted.
