### ISSUE TITLE
Initial Research - Similar Papers

### ISSUE THREAD

**Issue by ersoykadir** [ersoykadir/Requirement-Traceability-Analysis#3]
### Issue Description

We have started on researching similar papers on topics like requirements analysis and requirements tracking. We need to document the results on wiki.

### Step Details

Steps that will be performed:
- [x] Find similar papers and researches
- [x] Document them with summaries on wiki.

### Final Actions

Wiki page for initial research must be reviewed.

### Deadline of the Issue

23.59 - 23.02.2023

**Comment by codingAku** [comment]
I will summarize the _Analyzing Quality of Software Requirements; A
Comparison Study on NLP Tools_ and _Software Requirement Analysis: Research Challenges
and Technical Approaches_ for this task.

**Comment by codingAku** [comment]
The [wiki page](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Similar-Researches-on-Requirement-Analysis) is created with introduction and one summary. Please do follow the similar layout.

**Comment by ersoykadir** [comment]
I will summarize 
* Requirements Analysis Tool: A Tool for Automatically Analyzing Software Requirements Documents
* An Extendable Approach to Computer-Aided Software Requirements Engineering
First one is completed and added to wiki.

**Comment by ersoykadir** [comment]
> The [wiki page](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Similar-Researches-on-Requirement-Analysis) is created with introduction and one summary. Please do follow the similar layout.
> 
> UPDATE : Second summary and authors added. Open for review.

Reviewed both summaries. LGTM. It seems like the first paper(comparative study) mentions a tool called RAT which is also mentioned in the paper I read. Yours has abbreviated from Requirements Assessment Tool and mine from Requirements Analysis Tool so they might be different but I am curious if they have any relation. Also could you add publish dates of papers at the beginning.

**Comment by codingAku** [comment]
> > The [wiki page](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Similar-Researches-on-Requirement-Analysis) is created with introduction and one summary. Please do follow the similar layout.
> > UPDATE : Second summary and authors added. Open for review.
> 
> Reviewed both summaries. LGTM. It seems like the first paper(comparative study) mentions a tool called RAT which is also mentioned in the paper I read. Yours has abbreviated from Requirements Assessment Tool and mine from Requirements Analysis Tool so they might be different but I am curious if they have any relation. Also could you add publish dates of papers at the beginning.

Thank you. Yes, I also consider them being the same tool, however, the name and the publishers are different. Publish dates and platforms added accordingly.

**Comment by ersoykadir** [comment]
> I will summarize
> 
> * Requirements Analysis Tool: A Tool for Automatically Analyzing Software Requirements Documents
> * An Extendable Approach to Computer-Aided Software Requirements Engineering
>   First one is completed and added to wiki.

Second summary is completed. However, I chose to summarize `QuARS A NLP Tool for Requirements Analysis` paper instead of the second one mentioned above. We can take a look at that paper later on if needed but it was published in 1977 and reading through its first two pages seemed like it might not be helpful for now. From what I understood, they have developed a language to write requirements in, allowing them to be easily parsed and used for analysis. But it almost looks like a programming language from what I've read.

**Comment by codingAku** [comment]
> > I will summarize
> > 
> > * Requirements Analysis Tool: A Tool for Automatically Analyzing Software Requirements Documents
> > * An Extendable Approach to Computer-Aided Software Requirements Engineering
> >   First one is completed and added to wiki.
> 
> Second summary is completed. However, I chose to summarize `QuARS A NLP Tool for Requirements Analysis` paper instead of the second one mentioned above. We can take a look at that paper later on if needed but it was published in 1977 and reading through its first two pages seemed like it might not be helpful for now. From what I understood, they have developed a language to write requirements in, allowing them to be easily parsed and used for analysis. But it almost looks like a programming language from what I've read.

Thank you. I've reviewed both summaries and I agree that a newer research will be more relevant. Issue closed.
