### ISSUE TITLE
Create Custom Sidebar and Meeting Template

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#4]
### Issue Description

A custom sidebar to boost organization and provide easy access to wiki pages are needed. Existing wiki pages must be linked.
Secondly, a meeting template that includes **time, zoom link, agenda and the action items** shall be created.

### Step Details

Steps that will be performed:
- [x] Create a custom sidebar and link existing pages
- [x] Create a meeting template

### Final Actions

Review is needed to finalize.

### Deadline of the Issue

23.59 - 24.02.2023

**Comment by codingAku** [comment]
The [sidebar](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki) and the [meeting notes template](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Meeting-Notes-Template) is ready for review.

**Comment by ersoykadir** [comment]
Both looks perfect, thanks for the effort.
