### ISSUE TITLE
Initial Research - Traceability

### ISSUE THREAD

**Issue by ersoykadir** [ersoykadir/Requirement-Traceability-Analysis#5]
### Issue Description

We have settled on `Traceability` as our research topic. We need to do a literature review for Traceability.
We can do keyword search on title, abstracts and keywords. Also we might look on references of found papers to extend our research.
- Keywords(Open to improvements):
  - Requirements Traceability
  - Traceability Link Recovery
- Conferences: 
  - RE, RESFQ, ICSE
- People: 
  - [Jane Huffman Hayes](https://scholar.google.com/citations?user=vDBB56cAAAAJ&hl=en) - [Jane Cleland Huang](https://scholar.google.com/citations?user=IQ5XCgYAAAAJ&hl=en)
- [A paper on Literature Review of Issue-Based Requirement Traceability](https://ieeexplore.ieee.org/abstract/document/10036417). This can also be viewed.
- Also look for ICSE artifact repositories on github.

Side Note: Read papers carefully, evaluate if they are easy to read, look for the methods they used to present their content. Also keep in mind,
 - What can I do to improve this research, how it can be extended.
 - What methods has been used (NLP...)
 - Is it implemented, if so, look for the codes.

### Step Details

Steps that will be performed:
- [x] Find similar papers and researches.
- [x] Document them with summaries on wiki.

### Final Actions

Wiki page for the research must be reviewed.

### Deadline of the Issue

23.59 - 04.03.2023

**Comment by codingAku** [comment]
Research papers which their summary added:

- PRO-ART: Enabling Requirements Pre-Traceability
- A Framework for Requirements Traceability in UML-based Projects
- Issues in the development of a requirements traceability model
- An analysis of the requirements traceability problem
- Implementing requirements traceability: a case study

Please do check [Wiki](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Similar-Researches-on-Requirement-Analysis) for review.

**Comment by ersoykadir** [comment]
Papers which their summaries added:
- Traceability Fundamentals
- Improving Requirements Tracing via Information Retrieval
- Best Practices for Automated Traceability
- Automating Traceability Link Recovery through Classification
Especially the first paper was introducing many terms related to traceability, we can move some of the definitions from there to our glossary.
After the meeting tomorrow, I will review the papers @codingAku added and then we can close this issue.

**Comment by ersoykadir** [comment]
> Research papers which their summary added:
> 
> * PRO-ART: Enabling Requirements Pre-Traceability
> * A Framework for Requirements Traceability in UML-based Projects
> * Issues in the development of a requirements traceability model
> * An analysis of the requirements traceability problem
> * Implementing requirements traceability: a case study
> * TraceLab: An Experimental Workbench for Equipping Researchers to Innovate, Synthesize, and Comparatively Evaluate Traceability Solutions
> 
> Please do check [Wiki](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Similar-Researches-on-Requirement-Analysis) for review.

I have reviewed these. Also we did discuss them in Meeting 2. I have corrected couple spelling mistakes but other than that, they look good.
After @codingAku's review we can close this issue.
