### ISSUE TITLE
Setting up Milestones

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#6]
### Issue Description

Milestones are essential in any software project to improve the level of organization. In this context, we need to set some fundamental milestones to set a clearer roadmap.
These include:
- Literature Research ( 2 weeks)
- Development Phase (5 weeks)
- Evaluation Phase(3 weeks)
- Documentation Phase(3 weeks)

### Step Details

Steps that will be performed:
- [x] Create milestones on issues section
- [x] Link issues to the milestone

### Final Actions

Although the milestones will set general deadlines, changes may happen on the schedule.

### Deadline of the Issue

23.59 - 04.03.2023

**Comment by codingAku** [comment]
Please do see the [Milestones](https://github.com/ersoykadir/Requirement-Traceability-Analysis/milestones?with_issues=no) section.

**Comment by ersoykadir** [comment]
Looks good, thanks for the effort.

**Comment by codingAku** [comment]
After Meeting 2, the headlines for milestones require change and the Midterm report needs to be added.

**Comment by codingAku** [comment]
Please do check the updated version of the [Milestones](https://github.com/ersoykadir/Requirement-Traceability-Analysis/milestones?with_issues=no)

**Comment by ersoykadir** [comment]
LGTM
