### ISSUE TITLE
Creating Glossary Page

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#7]
### Issue Description

A glossary page containing formal definition to keywords related to the project development is needed to create on wiki.

### Step Details

Steps that will be performed:
- [x] Create a glossary page
- [x] Include keywords and reference
- [x] Add hyperlink to sidebar.

### Final Actions

The glossary page will be updated frequently with the progress in the project.

### Deadline of the Issue

5.03.2023 - 23.59

**Comment by codingAku** [comment]
First keywords added to wiki along with source. Please do check the [Glossary](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Glossary) page.

**Comment by ersoykadir** [comment]
Extended the [Glossary](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Glossary). We can close this issue after review from @codingAku. Glossary can be extended again in the future

**Comment by codingAku** [comment]
I believe it's sufficient for the current situation. There is a **_re-open_** label for future work on the issue.
