### ISSUE TITLE
Evaluation of Bounswe Repos - 2022 Group 3 and Group 2

### ISSUE THREAD

**Issue by codingAku** [ersoykadir/Requirement-Traceability-Analysis#9]
### Issue Description

As discussed in [Meeting 3](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Meeting-3---13.03.2023), some repos in [Bounswe](https://github.com/bounswe) will be evaluated manually. This means the requirements and their traces on commit messages, issue and PR descriptions and any other artifact will be noted. At the same time, the time each requirement took to complete will be noted. Moreover, if duplicate requirements exist, they will be pointed out. 

In addition, frequently used keywords in any software artifact need to be noted for similarity analysis is required. If the number of issues related to a requirement is higher than usual, the work taken by it should be documented as well. 

For the final evaluation, the requirements that have been completed and the ones that have not been implemented should be noted to show the progress the application has. 

The findings will overall show a quality analysis of the project based on requirements.

### Step Details

Projects to be evaluated:
- [x] [Learnify](https://github.com/bounswe/bounswe2022group2) - by @ersoykadir 
- [x] [BUcademy](https://github.com/bounswe/bounswe2022group3) - by @codingAku 

### Final Actions

The findings need to be documented on the project Wiki. 

### Deadline of the Issue

19.03.2023 - 23.59

**Comment by codingAku** [comment]
BUcademy evaluation is ready at the newly created [Wiki](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Evaluations-of-Bounswe-Projects) page.

**Comment by ersoykadir** [comment]
Learnify evaluation and notes added. Both BUcademy and Learnify findings were discussed in this week's [meeting](https://github.com/ersoykadir/Requirement-Traceability-Analysis/wiki/Meeting-4---20.03.2023). We can conclude this issue after @codingAku's review.

**Comment by codingAku** [comment]
I believe your notes are reflecting last week's discussion. No typo seen. Thank you.
